export const youtubeSx = {
  bodyYoutube: {
    right: "0",
    left: "0",
    top: "0",
    bottom: "0",
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    height: { xs: "680px", md: "904px" },
    backgroundImage: 'url("../../../image/Background Section 2.jpg")',
    backgroundSize: "cover",
    backgroundPosition: "center",
  },
  containerYoutube: {
    display: "flex",
    justifyContent: { xs: "center", md: "space-between" },
    alignItems: "center",
    height: "100%",
    flexDirection: { xs: "column", md: "unset" },
  },
  youtubeSite: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: { xs: "10px", md: "40px" },
  },
  textMain: {
    width: { xs: "320px", md: "655px" },
    fontWeight: "400",
    fontSize: { xs: "18px", md: "36px" },
    lineHeight: { xs: "23px", md: " 45px" },
    textAlign: "center",
    letterSpacing: "0.05em",
    fontFamily: "Merriweather",
    fontStyle: "normal",
    color: "white",
  },
  imageHero: {
    width: { xs: "320px", md: "unset" },
    height: { xs: "234px", md: "unset" },
    marginBottom: { xs: "60px", md: "unset" },
  },
  backgroundImage: {
    backgroundImage: 'url("../../../image/Video Background.png")',
    width: { xs: "360px", md: "655px" },
    height: { xs: "208px", md: " 378px" },
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundSize: "cover",
  },
};
